### ISSUE TITLE
Revamping LU file format and supported concepts

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botframework-cli#137]
# LU file format - new features and refinements
This document is a specification for improvements to the LU file format to include new features, capabilities. 

- [x] ~[Revamping entity definition](#new-entities)~ : **PR #168**
    - [Entity definition](#Entity-declaration-and-definition)
        - [Declaration only](#Declaration-only)
        - [Roles](#Roles)
        - [Features](#Features)
        - [Entity definition](#Entity-definition)
    - [Simple entity](#Simple-entity)
    - [Prebuilt entity](#Prebuilt-entity)
    - [List entity](#List-entity)
    - [Composite entity](#Composite-entity)
    - [Regex entity](#Regex-entity)
    - [Phrase list](#Phrase-list)
- [x] ~[nDepth entity, **NEW LUIS feature for Ignite 2019**](#ndepth)~ : **PR #193**
- [x] ~[Model as features **NEW LUIS feature for Ignite 2019**](#Model-as-feature)~ : **PR #177**
- [x] ~[Features to model **NEW LUIS feature for Ignite 2019**](#featureToModel)~ : **PR #172**
- [x] ~[Updates to labelling expereince](#Updates-to-labelling-expereince)~ : **PR #168**
- [Suppor for nested intents **REQUIRED for composer**](#Suppor-for-nested-intents)
- Docs updates
   - https://github.com/microsoft/botframework-cli/pull/148

## New entities
Today, ludown uses convoluted syntax to represent entities. This proposal is to streamline entity definition for composer use cases.

Should this resonate in composer, we will consider baking this into the core .lu file format.

Ludown supports the following LUIS entity types -

| Type                          | Ludown definition                                                 |
|-------------------------------|-------------------------------------------------------------------|
| Simple entity                 | $ \<entityName> : simple                                          |
| Simple entity with roles      | $ \<entityName> : simple Roles = role1, role2                     |
| Regex entity                  | $ \<entityName> : /regex pattern/                                 |
| Regex entity with roles       | $ \<entityName> : /regex pattern/ Roles = role1, role2            |
| Composite entity              | $ \<entityName> : [child1, child2, ...]                           |
| Composite entity with roles   | $ \<entityName> : [child2, child2, ...] Roles = role1, role2      |
| prebuilt entity               | $ PREBUILT : \<prebuilt-entity-type>                              |
| prebuilt entity with roles    | $ PREBUILT : \<prebuilt-entity-type> Roles = role1, role2         |
| List entity                   | $ \<entityName> : \<normalizedValue> =                            |
| List entity with roles        | $ \<entityName> : \<normalizedValue> = Roles = role1, role2       |
| phrase list                   | $ \<phraseListName> : phraseList                                  |

Mapping back to typical programming language constructs for variables -
- types: simple, regex, composite, list, all pre-built types (datetimeV2, age, dimension, email, money, number, ordinal, percentage, phoneNumber,temperature, url, datetime, keyPhrase, personName, geographyV2)
- roles: instance of an entity (name + type)

With that, here's the proposed entity declaration with type specification for LU -

@ \<entity-type> \<entity-name> [[hasRoles] \<comma-separated-list-of-roles>]

Entities that require a definition (e.g. list, regex, composite etc) are represented using this notation - 

@ \<entity-name> = \<definition>

Declaration and definition can also be combined into a single line like this -

@ \<entity-type> \<entity-name> [[hasRoles] \<comma-separated-list-of-roles>] = \<definition>

Entity type, entity name and definition are required. Roles,  are optional.

Entity names with space in them can be wrapped in quotes.

**Note:** prebuilt entity names cannot have spaces in them.

Here's an example:

```markdown
@ simple "this is a simple entity" role1, role2
@ simple 'this is a simple entity' hasRoles role1, role2
```

### Declaration only

```markdown
@ simple name
```

### Roles
```markdown
@ simple name role1, role2

> this is the same as 
@ simple name hasRoles role1, role2

> this is also the same as 
@ simple name
@ name hasRoles role1, role2

> Also same as 
@ simple name
@ name hasRole role1
@ name hasRole role2
```

### Features
```markdown
@ simple name role1, role2 
@ name usesFeature feature1, feature2

> Also same as 
@ simple name
@ name hasRoles role1, role2
@ name usesFeatures feature1, feature2
``` 

### Entity definition
```markdown
> For entities that need definition e.g. regex, composite, list, n-depth simple, we will support both inline definition as well as separtion of declaration and definition.
@ composite deviceTemperature from, to
@ deviceTemperature =
    - child1, child2

> Also same as 
@ composite deviceTemperature from, to = [child1, child2]
```

## Simple entity

```markdown
@ simple name firstName, lastName
```

## Prebuilt entity

```markdown
@ prebuilt number numOfGuests, age
@ prebuilt datetimeV2 fromDate, toDate
@ prebuilt age userAge
```

## List entity

```markdown
@ list color favColor, screenColor
@ color =
    - \<normalized-value>
        - \<synonym1>
        - \<synonym2>
        - ...
    - \<normalized-value>
        - \<synonym1>, \<synonym2>, ...
    - \<normalized-value>
        - \<synonym1>; \<synonym2>; ...
 
> Alternate definition
 
@ list color favColor, screenColor =
    - \<normalized-value>
        - \<synonym1>
        - \<synonym2>
        - ...
    - \<normalized-value>
        - \<synonym1>, \<synonym2>, ...
    - \<normalized-value>
        - \<synonym1>; \<synonym2>; ...
```

## Composite entity

```markdown
@ composite deviceTemperature from, to
@ deviceTemperature =
    - child1, child2

> Alternate definition

@ composite deviceTemperature from, to = [child1, child2]
```

## Regex entity

```markdown
@ regex hrf-number from, to
@ hrf-number = /hrf-[0-9]{6}/

> Alternate definition
@ regex hrf-number from, to = /hrf-[0-9]{6}/
```

## Phrase list

```markdown
@ phraseList todo
@ phraseList todo(interchangeable) =
    - \<value-as-list>
    - \<value-as-comma-separated-list>
    - \<value-as-semicolon-separated-list>
```
<a id="ndepth"></a>

## [New] Simple entity with n-depth support

LUIS will introuduce a new simple entity type that supports N-depth hierarchy. LUIS in V3 authoring API will deprecate the current composite & hierarchical entity types. 

Here's a definition of an `address` n-depth entity with `fromAddress` and `toAddress` as two roles.

```markdown
@ list city
@ prebuilt number
@ regex zipcode = /[0-9]{5}/
> Ignore the type name `simple-n-depth. We can call this what ever LUIS UX will snap to. 
@ nDepth address hasRoles fromAddress, toAddress 
@ address =
    - 'door number' dependsOn number
    - streetName
    - location usesFeature geographyV2
        - city dependsOn city
        - zipcode dependsOn zipcode
```

`dependsOn`:  
    - can only refer to other non-machine learned entity types including list, regex, prebuilt.
    - cannot be to a role of an entity
    - Is not available for non-leaf children.

`usesFeature`: 
    - A child (immaterial of its depth) can have both `dependsOn` and `usesFeature` relationship

Entity name cannot have `$` or `:` in it. 

## Model as feature

LUIS will introduce a new model as a feature concept. With this, models (all intents and entity types) can be used as a feature to another model (intent and entities). 

Constraints: 
1. Cirular model as feature is not supported. e.g. A isFeatureTo B and B isFeatureTo A. 
2. Both source model and target model should be defined and exist in the application.
3. An entity, phrase list and intent all can have the same name. So when an ambiguous definition appears on either the left or ride side of `usesFeature`, we should throw a parsing error that calls out the ambiguity. 
    E.g. user could have intent named `city` and an entity named `city` as well as a phrase list named `city`. If user tries to do @ city usesFeature geographyV2, `city` in this definition is ambiguous since it is not clear which specific `city` user would like to add `geographyV2` as a feature. In this case, the parser should throw an error and state `city` is ambiguous. Found an intent, phrase list and entity with that name. Consider renaming the overlapping concepts to establish a usesFeature relationship. 

Here's how you define entity as a feature to another entity - with `usesFeature`.

```markdown
> entity definition - <> \<entityType> \<entityName> [<roles>]
@ prebuilt personName
@ prebuilt age

> entity definition with roles
@ simple userName fistName, lastName

> add entity as feature to another entity
@ userName usesFeature personName

> add entity as feature to intent
@ getUserNameIntent usesFeature personName

> Intent definition
# getUserNameIntent
- utterances

> entity as feature to multiple models - in this case another entity and an intent
@ userName, getUserNameIntent usesFeature personName

> multiple entities as feature to a model
@ getUserNameIntent usesFeature age, personName

> multiple models as features to multiple models
@ userName, getUserNameIntent usesFeature age, personName

> intent as feature to another intent
@ getUserProfileIntent usesFeature getUserNameIntent

# getUserProfileIntent
- utterances
```

<a id="featureToModel"></a>

## Tie features to a specific model
Phrase lists today apply to all models in an application. LUIS is changing this to provide users more fine grained control where users can explicitly assign a phrase list as a feature to another model. With this, phrase list can be added as a feature to 

- another intent
- another entity
- child in an n-depth entity

Here's how you define phrase list as a feature to another model

```markdown
> phrase list definition
@ phraseList city(interchangeable) = 
    - seattle
    - space needle
    - SEATAC
    - SEA

> phrase list as feature to intent (also applicable to entities)
@ getUserProfileIntent usesFeature city

> phrase list as feature to n-depth entity with phrase list as a feature
@ simple-n-depth address fromAddress, toAddress
@ address =
    - 'door number' dependsOn number
    - streetName
    - location
        - city
        - zipcode dependsOn zipcode
```

### Open items
- We need to align the names of concepts with the portal experience. The following are subject to change and will likely be closed before end of September
    - nDepth
    - usesFeature
    - dependsOn

# Updates to labelling expereince

Here's what we have today -

| Scenario                                  | example                                                           |
|-------------------------------------------|-------------------------------------------------------------------|
| Labelled simple entity                    | My name is {userName = vishwac}                                   |
| Labelled simple entity with role          | My name is {userName:firstName = vishwac}                         |
| simple entity in pattern                  | My name is {userName}                                             |  
| simple entity with role in pattern        | My name is {userName:firstName}                                   |
| regex, prebuilt, list entity labels       | ** cannot be labelled **                                          |
| regex entity with role in utterance       | Can you deliver to {zipCode:delivery = 98052}?                    |
| regex entity with role in pattern         | Can you deliver to {zipCode:delivery}?                            |
| list entity with role in utterance        | My favorite color is {color:favoriteColor = red}                  |
| list entity with role in pattern          | My favorite color is {color:favoriteColor}                        |
| prebuilt entity with role in utterance    | My departure date is {datetimeV2:departureDate = tomorrow at 3pm} |
| prebuilt entity with role in pattern      | My departure date is {datetimeV2:departureDate}                   |

Given the role names must be **unique** across the application, we could drop the entity name from explicit labelling for a role.

| Scenario                                  | example                                                           |
|-------------------------------------------|-------------------------------------------------------------------|
| Labelled simple entity                    | My name is {userName = vishwac}                                   |
| Labelled simple entity with role          | My name is {firstName = vishwac}                                  |
| simple entity in pattern                  | My name is {userName}                                             |  
| simple entity with role in pattern        | My name is {firstName}                                            |
| regex, prebuilt, list entity labels       | ** cannot be labelled **                                          |
| regex entity with role in utterance       | Can you deliver to {delivery = 98052}?                            |
| regex entity with role in pattern         | Can you deliver to {delivery}?                                    |
| list entity with role in utterance        | My favorite color is {favoriteColor = red}                        |
| list entity with role in pattern          | My favorite color is {favoriteColor}                              |
| prebuilt entity with role in utterance    | My departure date is {departureDate = tomorrow at 3pm}            |
| prebuilt entity with role in pattern      | My departure date is {departureDate}                              |
 
Given composer uses @entityName to refer to an entity, we could consider supporting @entityName or @roleName to be consistent and familiar for users.

With those changes, here's what we will support -

| Scenario                                  | example                                                           |
|-------------------------------------------|-------------------------------------------------------------------|
| Labelled simple entity                    | My name is {@userName = vishwac}                                  |
| Labelled simple entity with role          | My name is {@firstName = vishwac}                                 |
| simple entity in pattern                  | My name is {@userName}                                            |  
| simple entity with role in pattern        | My name is {@firstName}                                           |
| regex, prebuilt, list entity labels       | ** cannot be labelled **                                          |
| regex entity with role in utterance       | Can you deliver to {@delivery = 98052}?                           |
| regex entity with role in pattern         | Can you deliver to {@delivery}?                                   |
| list entity with role in utterance        | My favorite color is {@favoriteColor = red}                       |
| list entity with role in pattern          | My favorite color is {@favoriteColor}                             |
| prebuilt entity with role in utterance    | My departure date is {@departureDate = tomorrow at 3pm}           |
| prebuilt entity with role in pattern      | My departure date is {@departureDate}                             |

## Suppor for nested intents
Nested intents help authors keep related intents + entity definitions together. This will also be helpful for tools like designer to capture and represent intents that aid and are relevant/ applicable to a specific conversation sub-flow. 

In order to support this, we will leverage markdown's ability to represent sections and subsections. 

```markdown
# section
## intentDefintion1
- utterances
- utterances

@ simple entityName
> Additional entity or other LU constructs
> ...

## intentDefintion2
- utterances
- utterances

> additional entity definitions or other LU constructs
> ...
```

**Rules for interpretation:** 
- An .lu document that contains section definition must include a parser delcaration to turn on sections parsing. By default, sections are not supported in .lu format.
- A section is identified by a single '#' section definiton and must contain another intent definition with '##' as the first line within that section. 
- Section names must be unique within the context of an .lu file being parsed. 
- All intent definitions within that section must start with '##'. 
- Use of '##' to represent an intent outside of a section behaves the same way as it does today (treated as a regular intent definition)
- A section ends when 
    - Another section definition begins
    - Another intent definition begins
- Sections defined across LU files are not collated and conflicts result in parser error. As an example, if 1.lu defines section1 with intent1 and 2.lu defines section1 with intent2, ludown parse with these two files will result in a parser error - Inconsistent definition found for `section1` - sections cannot be defined across multiple .lu files.
- Parser can do one of two possible things with sections 
    - [Default behvaior with @sections parsing enabled] Return a LUIS model definition with all intents within a section merged into a single intent named after the section name
    - Return a LUIS model definition with all intents within a section preserved as separate intents with individual intent names as '\<section-name>.\<intent-name>'
    - All entities and roles defined within all sections are de-duped and merged with the entities list in the LUIS application.

```markdown
> Enable section parsing (Disabled by default)
> !# @sections 

> Direct parser output to merge intents to a single intent named after the section-name (Default behavior)
> !# @sections.mergeIntents

> Provide a different name for merged intents for each section
> !# @sections.mergeIntents = sectionName : \<name-of-section>; intentName : \<name-of-output-intent>

> Valid section definition
# section
## intent1

> start and end of section1
# section1
## intent1
## intent2
> end of section1
# intent3 

> Invalid section definition
# section
### intent1

> Invalid section definition
# section
@ simple entityName

> Invalid section definition - in this case, both section and intent1 are interpreted as just two regular intent definitions. 
# section
# intent1
```

**Parser interface:**
We will add a new parser interface to break down a given .lu file content by intent/ sections. The required interfaces here need to be similar in capability offered by LG and should include the following - 

- Ability to parse a given .lu file content by intent name, body. Body should include all text content between intent definitions and includes any entity definitions, comments found within that block.
- Each section is treated as if it was a separate .lu file in that a nested structure of intent name, body for content within a section is made available. 
- Provide an interface that supports find, read, write opearations for body content to a .lu file given the intent name and optionally a section name. 
- Add two new methods to the parser interface. Both will throw an exception on errors (e.g. duplicate intent definition found, no section exists by given name, no intent exists by given name, etc)
    - parser.extractBody(fileContent, intentName, sectionName = null)
    - parser.writeBody(fileContent, body, intentName, sectionName = null)

**Comment by vishwacsena** [comment]
@boydc2014 is implementing supported for nested intents.
